from typing import Dict, Tuple

KIWI_USER_WORDS = [
    ("안전화", "NNG", 0.0),
    ("욕실화", "NNG", 0.0),
    # 조선업/건설·제조 직업명(-공 접미사) — Kiwi가 "용접"+"공"처럼 어근+접미사로
    # 쪼개면서 "공"을 접미사가 아니라 별도 명사(공/球 등)로 잘못 해석해 구조(Noun
    # Phrase)와 글로스("ball" 등)가 둘 다 틀어지던 문제. 이미 한 단어로 인식되는
    # 취부공/조적공/전공/목공/연마공/선반공/조공은 등록 불필요(제외).
    ("용접공", "NNG", 0.0),
    ("배관공", "NNG", 0.0),
    ("비계공", "NNG", 0.0),
    ("도장공", "NNG", 0.0),
    ("철근공", "NNG", 0.0),
    ("형틀공", "NNG", 0.0),
    ("방수공", "NNG", 0.0),
    ("미장공", "NNG", 0.0),
    ("도금공", "NNG", 0.0),
    ("기계공", "NNG", 0.0),
    ("절단공", "NNG", 0.0),
    ("성형공", "NNG", 0.0),
    ("재단공", "NNG", 0.0),
]

POS_MAP = {
    "NNG": "명사",
    "NNP": "명사",
    "NNB": "의존 명사",
    "NR": "수사",
    "NP": "대명사",
    "VV": "동사",
    "VA": "형용사",
    "VX": "보조 동사",
    "VCP": "품사 없음",
    "VCN": "품사 없음",
    "MM": "관형사",
    "MAG": "부사",
    "MAJ": "부사",
    "IC": "감탄사",
    "JKS": "조사",
    "JKC": "조사",
    "JKG": "조사",
    "JKO": "조사",
    "JKB": "조사",
    "JKV": "조사",
    "JKQ": "조사",
    "JX": "조사",
    "JC": "조사",
    "EP": "어미",
    "EF": "어미",
    "EC": "어미",
    "ETN": "어미",
    "ETM": "어미",
    "XPN": "접사",
    "XSN": "접사",
    "XSV": "접사",
    "XSA": "접사",
    "XSM": "접사",
    "XR": "품사 없음",
    "SF": "품사 없음",
    "SP": "품사 없음",
    "SS": "품사 없음",
    "SSO": "품사 없음",
    "SSC": "품사 없음",
    "SE": "품사 없음",
    "SO": "품사 없음",
    "SW": "품사 없음",
    "SL": "품사 없음",
    "SH": "품사 없음",
    "SN": "숫자",
    "SB": "품사 없음",
    "UN": "품사 없음",
}

POS_ENG_MAP = {
    "NNG": "Noun",
    "NNP": "Proper Noun",
    "NNB": "Bound Noun",
    "NR": "Number",
    "NP": "Pronoun",
    "VV": "Action Verb",
    "VA": "Descriptive Verb",
    "VX": "Auxiliary Verb",
    "VCP": "품사 없음",
    "VCN": "품사 없음",
    "MM": "Determiner",
    "MAG": "Adverb",
    "MAJ": "Connecting Adverb",
    "IC": "Interjection",
    "JKS": "Particle",
    "JKC": "Particle",
    "JKG": "Particle",
    "JKO": "Particle",
    "JKB": "Particle",
    "JKV": "Particle",
    "JKQ": "Quote",
    "JX": "Particle",
    "JC": "Particle",
    "EP": "Suffix",
    "EF": "Sentence end",
    "EC": "Connector",
    "ETN": "Suffix",
    "ETM": "Suffix",
    "XPN": "Substantive Prefix",
    "XSN": "Noun-modifying Suffix",
    "XSV": "품사 없음",
    "XSA": "품사 없음",
    "XSM": "Suffix",
    "XR": "품사 없음",
    "SF": "품사 없음",
    "SP": "품사 없음",
    "SS": "품사 없음",
    "SSO": "품사 없음",
    "SSC": "품사 없음",
    "SE": "품사 없음",
    "SO": "품사 없음",
    "SW": "품사 없음",
    "SL": "품사 없음",
    "SH": "품사 없음",
    "SN": "Number",
    "SB": "품사 없음",
    "UN": "품사 없음",
}

FORM_POS_ENG_OVERRIDE: Dict[Tuple[str, str], str] = {
    ("겠", "EP"): "Tense Form",
    ("으시", "EP"): "Particle",
    ("시", "EP"): "Particle",
}
